### ISSUE TITLE
Audio issue for premiere pro 

### ISSUE THREAD

**Issue by Lee-Yi-Loong-Clarence** [JulianDominic/Python-yt-dlp#2]
Help your new version with the audio only download cannot work on premiere pro [Image](https://imgur.com/DPB4O2F)

**Comment by JulianDominic** [comment]
The source audio extensions are only `m4a` and `webm`. Out of these two, premiere pro can only work with `m4a` because `webm` is not supported. Use `m4a` for audio extension and `mp4a` for audio codec.
